name: dia_rest_example
description: A sample REST API server on Dia.
version: 1.0.0
homepage: https://github.com/unger1984/dia-rest-example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  dart_jsonwebtoken: ^2.0.1
  dia: ^0.1.1
  dia_body: ^0.1.0
  dia_cors: ^0.1.0
  dia_router: ^0.1.3
  dotenv: 3.0.0-nullsafety.0
  json_annotation: ^4.0.1
  path: ^1.8.0
  postgresql2: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0
  pedantic: ^1.11.0
  test: ^1.16.8
